spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: # Your Email
    password: # Your password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  # Because of security reasons, the profile "dev" has never been committed to Git.
  # So, you should either create the file application-dev.yml manually or simply remove that property
  profiles:
    active: dev